openapi: 3.0.0
info:
  title: WhatsApp API
  description: API Wrapper for WhatsAppWebJS
  version: 1.0.0
servers:
  - url: www.www.ws
    description: ''
  - url: http://localhost:3000
    description: localhost
  - url: https://www.google.com
    variables: {}
paths:
  /api:
    summary: aa
    description: '111'
    get:
      summary: aa
      description: '11'
      operationId: aaa
      responses:
        default:
          description: Default error sample response
          content:
            text/plain:
              examples:
                '{"response":"test"}':
                  value: '{"response": "test"}'
            application/json:
              examples:
                OK:
                  value: a
      tags:
        - API
